spring:
    application:
        name: securityMS
    security:
        user:
            name: nikita
        password: nikita
        roles: ADMIN
#    datasource:
#        driver-class-name: org.h2.Driver
#        password: password
#        url: jdbc:h2:mem:employee_db
#        username: sa
#    jpa:
#        hibernate:
#            ddl-auto: update
#        show-sql: true

server:
    port: 9090