spring:
    application:
        name: gateway
    main:
        allow-bean-definition-overriding: true
#        allow-circular-references: true
    cloud:
        gateway:
            routes:
                - id: department-service
                  uri: http://localhost:8091
                  predicates:
                      - Path=/departments/**

                - id: employee-service
                  uri: http://localhost:8080
                  predicates:
                      - Path=/employees/**
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true

    datasource:
        driver-class-name: org.h2.Driver
        password: password
        url: jdbc:h2:mem:employee_db
        username: sa
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 8095