eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8080
spring:
    application:
        name: employee-service
    datasource:
        driver-class-name: org.h2.Driver
        password: password
        url: jdbc:h2:mem:employee_db
        username: sa
#        url: mysql://localhost:3306/employee_db
#        username: root
#        password: Nikita@123!
#        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            group-id: empGroup