FROM FROM eclipse-temurin:17-jdk-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the packaged jar file into the container
COPY target/EmpProject-0.0.1-SNAPSHOT.jar EmpProject.jar

# Make port 8080 available to the world outside this container
EXPOSE 8091

# Run the jar file
ENTRYPOINT ["java", "-jar", "EmpProject.jar"]