spring.application.name=SpringSecurityOAuth2
spring.security.user.name =${SECURITY_USERNAME:nikita}
spring.security.user.password=${SECURITY_PASSWORD:nikita}
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=${LOGGING_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){green} %clr(%-5level){yellow} %clr(%logger{36}){cyan} - %clr(%msg){faint}%n}
logging.level.org.springframework.security=${LOGGING_LEVEL_SECURITY:Trace}