spring.application.name=SpringSecurityOAuth2
spring.security.user.name =${SECURITY_USERNAME:nikita}
spring.security.user.password=${SECURITY_PASSWORD:nikita}
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=${LOGGING_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){green} %clr(%-5level){yellow} %clr(%logger{36}){cyan} - %clr(%msg){faint}%n}
logging.level.org.springframework.security=${LOGGING_LEVEL_SECURITY:Trace}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23livRxqwT0t5jEXrt}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_ID:8ee1219ebe3c749b5191a013d0b39ff00666b98c}