spring.application.name=${SPRING_APPNAME:Authorization}
spring.config.import=application_prod.properties,application_dev.properties
spring.profiles.active=default

spring.datasource.url=jdbc:mysql://localhost:3306/bank_app_db
spring.datasource.username=root
spring.datasource.password=Nikita@123!
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=${LOGGING_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){green} %clr(%-5level){yellow} %clr(%logger{36}){cyan} - %clr(%msg){faint}%n}
logging.level.org.springframework.security=${LOGGING_LEVEL_SECURITY:Trace}
server.servlet.session.timeout=${SESSION_TIMEOUT:2m}

#property for oauth 2 with jwt token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_URI:http://localhost:9000/oauth2/jwks}

#property for oauth 2 with opaque token
#spring.security.oauth2.resourceserver.opaque.introspection-uri=${INTROSPECTION_URI:http://localhost:9000/oauth2/introspect}
#spring.security.oauth2.resourceserver.opaque.introspection-client-id=${INTROSPECTION_CLIENT_ID:bankapiintrospect}
#spring.security.oauth2.resourceserver.opaque.introspection-client-secret=${INTROSPECTION_CLIENT_SECRET:Kp3XvN7qLaZrC1oTybMGdWK4JfUH625Q}