spring.config.activate.on-profile=dev
spring.application.name=${SPRING_APPNAME:Authorization}

# Use the following lines to set the manual user and password for login
#spring.security.user.name =${SECURITY_USERNAME:nikita}
#spring.security.user.password=${SECURITY_PASSWORD:nikita}

spring.datasource.url=jdbc:mysql://localhost:3306/bank_app_db
spring.datasource.username=root
spring.datasource.password=Nikita@123!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=${LOGGING_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr([%thread]){green} %clr(%-5level){yellow} %clr(%logger{36}){cyan} - %clr(%msg){faint}%n}
logging.level.org.springframework.security=${LOGGING_LEVEL_SECURITY:Trace}
server.servlet.session.timeout=${SESSION_TIMEOUT:2m}